config/routes.rb
Buttress::Application.routes.draw do

  # Below we define all of our administrator namespace routes.. These are for site admin and site staff members only
  resources :admin, :only => [ :index ]
  namespace :admin do
    resources :users
  end

  # Routes for devise users (login logout register..etc)
  devise_for :users, :path => '', :path_names => {
      :sign_in => 'login',
      :sign_out => 'logout',          # must be method :DELETE
      :registration => 'register',    # /register POST
      :sign_up => 'new'               # /register/new
  }

  # Root path
  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    
    # initialize a new user
    user ||= User.new

    # allow reading of all
    can :read, :all

    # if admin, manage all
    if user.is_admin?
      can :manage, :all
    end
    
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  
  
  validates :first_name, :presence => true
  validates :first_name, :length => { maximum: 50 }

  validates :last_name, :presence => true
  validates :last_name, :length => { maximum: 50 }

  validates :email, :presence => true
  validates :password, :presence => true
  
  def full_name 
    "#{first_name} #{last_name}"
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery

  before_filter :authenticate_admin!
  before_filter :userDecoratorToView

  layout 'administration'

  def index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :userDecoratorToView

  private

  # A before filter to send a user decorator to the view
  def userDecoratorToView
    @authed_user = UserDecorator.decorate(current_user)
  end

  # A before filter for authing someone as an admin
  def authenticate_admin!
    redirect_to root_path unless current_user.present? && current_user.is_admin?
  end

  # Rescue from an access denied thrown by cancan
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then "info"
    when :error then "error"
    when :alert then "warning"
    when :success then "success"
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
  <div class="row">
    <div class="span12">Place holder for admin dashboard -- think graphs and what not.</div>
  </div>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @user] %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <%- model_class = User -%>
    <div class="page-header">
      <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
    </div>  
		<% if !@users.nil? && @users.count > 0 %>
    	<%= form_tag admin_users_path, :method => 'get' do %>
    	  <p>
    	    <%= text_field_tag :search, params[:search] %>
    	    <%= submit_tag "Search", :name => nil %>
    	  </p>
    	<% end %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Admin?</th>
            <th>Created</th>
            <th class='span2 center'>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.full_name, admin_user_path(user) %></td>
              <td><%= user.email %></td>
              <td><%= user.is_admin ? 'Yes' : 'No' %></td>
              <td><%= user.created_at.strftime("%d %b. %Y") %></td>
              <td class='span2 center'>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_admin_user_path(user), :class => 'btn btn-mini' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            admin_user_path(user),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-mini btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>	
		<%= will_paginate @users %>  
		
    <% end %>
    
    <%= link_to 'Create New User', new_admin_user_path, class: 'btn' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Created on:</b>
  <%= @user.created_at %>
</p>


<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Buttress <em><span class="def_type">n.</span> /ˈbətris/</em></h1>
  <p class="lead">A structure built against another structure to support it.</p>

  <hr>
  
  <h3>That's great, what does it do?</h3>
  <p class="lead">Buttress is a collection of popular gems designed for rapid prototyping and application development with the <a href="http://rubyonrails.org/">Ruby on Rails</a> framework.  We've put them together and built a bare-bones setup to help support your project from prototype to launch.</p>
</div>

<hr>

<div class="row-fluid marketing">
  <div class="span6">
    <h4>Built with Bootstrap</h4>
    <p>Take advantage of one of the hottest front-end frameworks available today: <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>.</p>

    <h4>GitHub Style Guided</h4>
    <p>We use <a href="https://github.com/styleguide/ruby">GitHub's ruby style guide</a> to light our way, making the code clean, concise, and easy.</p>
        
    <h4>Test driven</h4>
    <p>Buttress utilizes many gems, most with <a href="http://railscasts.com/">railscasts</a> episodes, that assist test driven development (TDD).  These include: <a href="https://github.com/rspec/rspec-rails">rspec-rails</a>, <a href="https://github.com/jnicklas/capybara">capybara</a>, <a href="https://github.com/thoughtbot/factory_girl_rails">factory_girl_rails</a>, among others listed in the wiki's <a href="https://github.com/JDStraughan/buttress/wiki/Gems-used-in-Buttress">gem list</a>.</p>
    
  </div>

  <div class="span6">
    <h4>Authentication</h4>
    <p>Buttress uses <a href="https://github.com/plataformatec/devise">Devise</a> to take the suck out of user auth. Since devise works nicely with <a href="https://github.com/intridea/omniauth">OmniAuth</a>, multi-provider access is only steps away.</p>
    
    <h4>Authorization</h4>
    <p><a href="https://github.com/ryanb/cancan">CanCan</a> makes user access and restriction a breeze, and it fits nicely on top of the authentication layer.</p>
    
    <h4>Admin area dried-in</h4>
    <p>It seems like every application needs an admin area, so we have one prepped and ready for final build out complete with user section containing search, pagination, and column sorting.</p>
    
  </div>
</div>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Buttress" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
</head>
<body role="<%= @body_role if @body_role.present? %>">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Buttress Administration", root_path, :class => "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Home", "https://github.com/JDStraughan/buttress"  %></li>
          <li><%= link_to "Wiki", "https://github.com/JDStraughan/buttress/wiki"  %></li>
          <li><%= link_to "Issues", "https://github.com/JDStraughan/buttress/issues"  %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <%= @authed_user.menu %>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path  %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="span12">

      <% [:notice, :error, :alert].each do |level| %>
        <% unless flash[level].blank? %>
          <div class="alert <%= flash_class(level) %>">
            <a class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :p, flash[level] %>
          </div>
        <% end %>
      <% end %>

      <%= yield %>
    </div>
  </div><!--/row-->

  <hr>

  <footer>
    <div class="pull-right">&copy; 2012 | <a href="http://mit-license.org/">MIT License</a></div>
  </footer>

</div> <!-- /container -->

<!-- Javascripts
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application" %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Buttress" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body role="<%= @body_role if @body_role.present? %>">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Buttress", root_path, :class => "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "https://github.com/JDStraughan/buttress"  %></li>
              <li><%= link_to "Wiki", "https://github.com/JDStraughan/buttress/wiki"  %></li>
              <li><%= link_to "Issues", "https://github.com/JDStraughan/buttress/issues"  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <%= @authed_user.menu %>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Register", new_user_registration_path  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <a href="https://github.com/JDStraughan/buttress" class="fork-me"><img src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

    <div class="container">
      <div class="row">
        <div class="span12">
          
      		<% [:notice, :error, :alert].each do |level| %>
      		  <% unless flash[level].blank? %>
      		    <div class="alert <%= flash_class(level) %>">
      		      <a class="close" data-dismiss="alert">&#215;</a>
      		      <%= content_tag :p, flash[level] %>
      		    </div>
      		  <% end %>
      		<% end %>
          
          <%= yield %>
        </div>
      </div><!--/row-->

      <hr>

      <footer>
        <div class="pull-right">&copy; 2012 | <a href="http://mit-license.org/">MIT License</a></div>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>